mail_hostname: mail.ondre.de
mail_primary_domain: ondre.de

certbot_mail_email: "ondre@ondre.de"

mail_domains:
  - ondre.de
  - faintphotons.de

mail_users:
  - name: ondre
    shell: /bin/bash
    create_home: true
  - name: hasi
    shell: /usr/sbin/nologin
    create_home: true

mail_aliases_local:
  - aliases: ["info", "moobert", "zemightyone"]
    targets: ["ondre"]
  - aliases: ["mohre"]
    targets: ["hasi"]
  - aliases: ["team"]
    targets: ["hasi", "ondre"]

postfix_virtual_alias_domains:
  - faintphotons.de

mail_aliases_virtual:
  - address: "info@faintphotons.de"
    target: "ondre"
  - address: "kontakt@faintphotons.de"
    target: "ondre"

opendkim_domains:
  - domain: ondre.de
    selector: mail2026
  - domain: faintphotons.de
    selector: mail2026