admin_user: "ondre"
vps_admin_ssh_keys: "{{ vault_vps_admin_ssh_keys }}"

# Sudo ohne Passwort für Ansible
vps_admin_sudo_nopasswd: true

docker_user: ondre
docker_group: ondre

fail2ban_enabled: true

fail2ban_defaults:
  backend: systemd
  bantime: 1h
  findtime: 10m
  maxretry: 3
  ignoreip:
    - 127.0.0.1/8
    - ::1

fail2ban_jails:
  sshd:
    enabled: true
    port: ssh

  dovecot:
    enabled: true
    port: imap,imaps,pop3,pop3s,submission,submissions,sieve

  postfix-sasl:
    enabled: true
    port: smtp,submission,submissions