### Legacy
wireguard_role: server
wireguard_interface: wg0
wireguard_port: 51820
wireguard_address: "10.42.0.1/24"

wireguard_primary_interface: wg0

wireguard_peers:
  - name: smallbox1
    allowed_ips:
      - "10.42.0.3/32"
    persistent_keepalive: 25
  
  - name: smallbox2
    allowed_ips:
      - "10.42.0.2/32"
    persistent_keepalive: 25
###


wireguard_external_interface: ens6

wireguard_port_forwards:
  - name: gitea_ssh
    proto: tcp
    public_port: 2222
    target_ip: "10.42.0.2"
    target_port: 2222

wireguard_instances:
  - name: mgmt
    interface: wg0
    port: 51820
    address: "10.42.0.1/24"
    port_forwards:
      - name: gitea_ssh
        public_port: 2222
        target_ip: "10.42.0.2"
        target_port: 2222
        proto: tcp
    peers:
      - name: smallbox1
        allowed_ips: ["10.42.0.3/32"]
        persistent_keepalive: 25
      - name: smallbox2
        allowed_ips: ["10.42.0.2/32"]
        persistent_keepalive: 25

  - name: ha_gw
    interface: wg1
    port: 51821
    address: "10.43.0.1/24"

    peers:
      - name: smallbox2
        interface: wg1
        allowed_ips:
          - "10.43.0.2/32"
          - "192.168.0.2/32"
        persistent_keepalive: 25