---

- name: Set mail user passwords
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password_hash }}"
    update_password: on_create
  loop: "{{ mail_users }}"
  when:
    - item.password_hash is defined