# roles/vps_base/handlers/main.yml

- name: Validate ssh config
  become: true
  ansible.builtin.command: /usr/sbin/sshd -t
  changed_when: false
  listen: Validate and reload ssh

- name: Reload ssh
  become: true
  ansible.builtin.service:
    name: ssh
    state: reloaded
  listen: Validate and reload ssh