---
- name: compile rspamd spam sieve script
  ansible.builtin.command:
    cmd: "sievec {{ dovecot_sieve_before_script }}"
  listen: compile rspamd spam sieve script

- name: restart dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted

- name: reload dovecot
  ansible.builtin.service:
    name: dovecot
    state: reloaded

- name: Validate fail2ban config
  become: true
  ansible.builtin.command: fail2ban-client -t
  changed_when: false
  listen: Validate and reload fail2ban

- name: Reload fail2ban
  become: true
  ansible.builtin.service:
    name: fail2ban
    state: reloaded
  listen: Validate and reload fail2ban
