---
- name: compile rspamd spam sieve script
  ansible.builtin.command:
    cmd: "sievec {{ dovecot_sieve_before_script }}"
  listen: compile rspamd spam sieve script

- name: restart dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted

- name: reload dovecot
  ansible.builtin.service:
    name: dovecot
    state: reloaded