---
rspamd_packages:
  - redis-server
  - rspamd

rspamd_redis_servers: "127.0.0.1:6379"

rspamd_controller_password_hash: ""

rspamd_milter_headers_extended: true
rspamd_milter_headers_authenticated:
  - x-spamd-result
  - x-rspamd-server
  - x-rspamd-queue-id
  - authentication-results

rspamd_multimap_enabled: true

rspamd_multimap_pharma_subject_patterns:
  - '/.*\bpillen\b.*/i'
  - '/.*\btabletten\b.*/i'
  - '/.*\brezeptfrei\b.*/i'
  - '/.*\breze-ptfrei\b.*/i'
  - '/.*\bre-zeptfrei\b.*/i'
  - '/.*\brezeptfre-i\b.*/i'
  - '/.*\bpotenz\b.*/i'
  - '/.*\bmanneskraft\b.*/i'
  - '/.*\b5x\b.*\bdurch\b.*/i'
  - /.*\bmeds?\b.*/i
  - /.*\bmedikamente?\b.*/i
  - /.*\bapotheke\b.*/i
  - /.*\bdoktor\b.*/i
  - /.*\bausdauer\b.*\bbett\b.*/i
  - /.*\bbett\b.*\bausdauer\b.*/i
  - /.*\bre[\W_]*zept[\W_]*frei\b.*/i
  - /.*\br[\W_]*ezept[\W_]*frei\b.*/i
  - /.*\bordern\b.*/i
  - /.*\bbestellen\b.*/i
  - /.*\bblutdruck\b.*/i
  - /.*\bnagelpilz\b.*/i
  - /.*\babnehmziele\b.*/i
  - /.*\bsema\s*7\b.*/i

rspamd_multimap_scam_subject_patterns:
  - '/.*\bwarnung\b.*cloud-speicher.*/i'
  - '/.*\blagerwarnung\b.*/i'
  - '/.*\brückerstattung\b.*/i'
  - '/.*\bbitte bestätigen sie ihre daten\b.*/i'
  - '/.*\baktualisierung\b.*\bfreigabeumgebung\b.*/i'
  - '/.*\bdkb\b.*\bhinweis\b.*/i'
  - '/.*\beasybank\b.*\bdaten\b.*/i'
  - /.*\bsecurego\b.*/i
  - /.*\bfreigabeumgebung\b.*/i
  - /.*\bkreditkarte\b.*\baktivieren\b.*/i
  - /.*\bdkb\b.*\bbank\b.*/i
  - /.*\beasybank\b.*/i
  - /.*\bnorton\b.*\blife\s*lock\b.*/i
  - /.*\bservice confirmation\b.*/i
  - /.*\bcloud-speicher\b.*\bvoll\b.*/i
  - /.*\bihr cloud-speicher ist voll\b.*/i
  - /.*\brückerstattung\b.*/i
  - /.*\bbestätigen sie ihre daten\b.*/i

rspamd_multimap_clickbait_subject_patterns:
  - '/.*\bbekannt aus tv\b.*/i'
  - '/.*\bdie höhle der löwen\b.*/i'
  - '/.*\boffiziell ausverkauft\b.*/i'
  - '/.*\bnotaufnahme\b.*/i'
  - '/.*\bneuer trend\b.*/i'
  - '/.*\bblitzer erkennen\b.*/i'
  - '/.*\bstrafzettel\b.*/i'
  - /.*\bblitzer\b.*/i
  - /.*\bstrafzettel\b.*/i
  - /.*\bautodiebstahl\b.*/i
  - /.*\bneuer trend\b.*/i
  - /.*\bnotaufnahme\b.*/i
  - /.*\bkühlschrank\b.*\bnotaufnahme\b.*/i
  - /.*\bkompressionsstrümpfe\b.*/i
  - /.*\bmüden beine\b.*/i
  - /.*\bkörperhaltung\b.*/i
  - /.*\brücken\b.*/i
  - /.*\bbrillenübersetzer\b.*/i
  - /.*\bki-sprachassistent\b.*/i
  - /.*\bansehen bevor es gelöscht wird\b.*/i
