---

- name: VPS Mail Server
  hosts: strato_vps
  gather_facts: true
  become: true
  roles:
    - role: mail_base
    - role: postfix
    - role: dovecot
    - role: certbot_mail
    - role: mail_users
    - role: mail_aliases
    - role: opendkim
    - role: rspamd
